#!/bin/bash -l
# Change this next list to run on a different number of nodes
#PBS -l nodes=1:ppn=1+4:ppn=2
#PBS -N cptest2
#PBS -m e
#PBS -v ASKAP_ROOT
cd $PBS_O_WORKDIR

module load openmpi

export AIPSPATH=$ASKAP_ROOT/Code/Components/Synthesis/testdata/current

mpirun -x AIPSPATH $ASKAP_ROOT/Code/Components/Synthesis/synthesis/current/install/bin/csimulator.sh -inputs cptest2.in > cptest2.out.$PBS_JOBID

mpirun -x AIPSPATH $ASKAP_ROOT/Code/Components/Synthesis/synthesis/current/install/bin/cimager.sh -inputs cptest2.in >> cptest2.out.$PBS_JOBID
