. ./ModuleFile
<<<<<<< HEAD
PREFIX=/group/askap/sord/yanda
export CPPFLAGS=" -fPIC "
../general/build_all.sh -w ${PREFIX}/factory -d -p ${PREFIX} -C "-DCMAKE_CXX_FLAGS=-Dcasa=casacore -DCFITSIO_ROOT_DIR=$CFITSIO_ROOT -DDATA_DIR=/group/askap/sord/yanda/share/casacore/data -DCMAKE_BUILD_TYPE=Release " -r -O "-DCMAKE_CXX_FLAGS=-Dcasa=casacore -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/group/askap/sord/yanda -DCFITSIO_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/cfitsio/3.420 -DWCSLIB_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/wcslib/5.18 -DFFTW_ROOT=/group/askap/sord/software/cle60up05/apps/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/fftw/3.3.8 -DCASACORE_ROOT_DIR=/group/askap/sord/yanda"
../general/build_all.sh -w ${PREFIX}/factory -d -p ${PREFIX} -a -O "-DCMAKE_CXX_FLAGS=-Dcasa=casacore -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/group/askap/sord/yanda -DCFITSIO_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/cfitsio/3.420 -DWCSLIB_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/wcslib/5.18 -DFFTW_ROOT=/group/askap/sord/software/cle60up05/apps/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/fftw/3.3.8 -DCASACORE_ROOT_DIR=/group/askap/sord/yanda"
../general/build_all.sh -w ${PREFIX}/factory -d -p ${PREFIX} -y -O "-DCMAKE_CXX_FLAGS=-Dcasa=casacore -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/group/askap/sord/yanda -DCFITSIO_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/cfitsio/3.420 -DWCSLIB_ROOT_DIR=/pawsey/cle60up05/devel/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/wcslib/5.18 -DFFTW_ROOT=/group/askap/sord/software/cle60up05/apps/PrgEnv-gnu/6.0.4/gcc/7.2.0/ivybridge/fftw/3.3.8 -DCASACORE_ROOT_DIR=/group/askap/sord/yanda"
=======
../general/build_all.sh -d -C "-DCFITSIO_ROOT_DIR=$CFITSIO_ROOT -DDATA_DIR=${PREFIX}/share/casacore/data -DCMAKE_BUILD_TYPE=Release " -r -a -y -e -O "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCFITSIO_ROOT_DIR=$CFITSIO_ROOT -DWCSLIB_ROOT_DIR=${MAALI_WCSLIB_HOME} -DFFTW_ROOT=${MAALI_FFTW_HOME}  -DCASACORE_ROOT_DIR=${PREFIX}"
>>>>>>> b7b8e9fcfda4e4996162afef1d4d4a6552345c7a
