#@file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env
import os
import sys

if 'AIPSPATH' not in os.environ:
   os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Base/accessors/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

#env.AppendUnique(CCFLAGS='-DASKAP_GRID_WITH_BLAS')
env.AppendUnique(CCFLAGS=['-DASKAP_GRID_WITH_POINTERS'])


# Optimization for complex arithmetic. The functionality this flag enables
# was default behaviour prior to GCC 4.3. However this option is not supported
# by clang, so don't use it on Mac
# On Mac use the inbuilt Accelerate framework so no longer get the linker flag from
# dependency analysis so need to make it explict here.
if sys.platform != 'darwin':
    env.AppendUnique(CCFLAGS=['-fcx-limited-range'])
else:
    env.AppendUnique(LINKFLAGS=['-llapack'])

env.AppendUnique(CCFLAGS=['-Wno-unused-local-typedefs'])

# create build object with library name
pkg = env.AskapPackage("synthesis")
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

# add sub packages 
pkg.AddSubPackage("utils")
pkg.AddSubPackage("measurementequation")
pkg.AddSubPackage("gridding")
pkg.AddSubPackage("parallel")
pkg.AddSubPackage("simulation")
pkg.AddSubPackage("deconvolution")
pkg.AddSubPackage("opcal")

# run the build process
pkg()

