# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env
import os

os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Components/Synthesis/testdata/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

#env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-DASKAP_GRID_WITH_BLAS', '-g'])
env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-DASKAP_GRID_WITH_POINTERS', '-g'])
env.Append(universal=0)

# create build object with library name
pkg = env.AskapPackage("synthutil")
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

# add sub packages 
pkg.AddSubPackage("calweightsolver")

# run the build process
pkg()

