# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env
import os

env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-DASKAP_GRID_WITH_POINTERS', '-g'])
env.Append(universal=0)

# create build object with library name
pkg = env.AskapPackage("testloadgridder")
pkg.build_shared = True;

# add sub packages 
pkg.AddSubPackage("testloadgridder")

# run the build process
pkg()

